[build-system]
requires = ["maturin>=1.9"]
build-backend = "maturin"

[project]
name = "examples-images"
dynamic = ["version"]
dependencies = ["numpy"]

[tool.maturin]
bindings = "pyo3"
python-packages = ["images"]
module-name = "images.core"
manifest-path = "Cargo.toml"
