[workspace]
members = ["egui-pysync-macros"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"

[package]
name = "egui_pysync"
version.workspace = true
edition.workspace = true

[features]
server = ["dep:pyo3"]

[dependencies]
egui_pysync_macros = { path = "egui-pysync-macros" }
postcard = { version = "1.1.1", features = ["use-std"] }
egui = "*"
serde = "1"
heapless = "0.7"
pyo3 = { version = "0.23", optional = true }
