[workspace]
members = [
    "egui-pysync-server",
    "egui-pysync-client",
    "egui-pysync-transport",
    "egui-pysync-macros",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace.dependencies]
egui_pysync_transport = { path = "egui-pysync-transport" }
egui_pysync_macros = { path = "egui-pysync-macros" }

[package]
name = "force-build"
edition.workspace = true

[[bin]]
name = "force-build"
path = "main.rs"
