[workspace]
members = ["crates/egui-pysync", "crates/egui-pysync-macros"]
resolver = "3"

[workspace.package]
version = "0.6.1"
edition = "2024"

[workspace.dependencies]
egui_pysync_macros = { path = "crates/egui-pysync-macros" }
egui_pysync = { path = "crates/egui-pysync" }
