[workspace]
members = [
    "egui-pysync-server",
    "egui-pysync-client",
    "egui-pysync-common",
    "egui-pysync-macros",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

# [package]
# name = "ExpertPI-gui"
# version.workspace = true
# edition.workspace = true

# [features]
# server = ["dep:pyo3", "states_server/server"]
# ui = [
#     "dep:eframe",
#     "dep:egui",
#     "dep:epaint",
#     "dep:egui_extras",
#     "dep:egui_plot",
#     # "dep:rayon",
#     "states_server/ui",
# ]

# [lib]
# name = "gui"
# crate-type = ["cdylib", "lib"]
# doctest = false

# [[bin]]
# name = "ExpertUI"
# path = "src/main.rs"
# required-features = ["ui"]

[workspace.dependencies]
egui_pysync_common = { path = "egui-pysync-common" }
# pyo3 = { version = "0.22.3", features = ["extension-module", "abi3-py311"] }
# egui = { version = "0.29.0", features = ["rayon"] }

# [dependencies]
# eframe = { version = "0.29.0", optional = true }
# egui = { workspace = true, optional = true }
# epaint = { version = "0.29.0", features = ["rayon"], optional = true }
# egui_extras = { version = "0.29.0", features = ["svg"], optional = true }
# egui_plot = { version = "0.29.0", optional = true }
# pyo3 = { workspace = true, optional = true }
# # rayon = { version = "1.10.0", optional = true }

# states_server = { workspace = true }
