[workspace]
members = [
    "egui-pyserver",
    "egui-pyclient",
    "egui-pysync",
    "egui-pymacros",
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"

[workspace.dependencies]
egui_pysync = { path = "egui-pysync" }
egui_pymacros = { path = "egui-pymacros" }

[package]
name = "force-build"
edition.workspace = true

[[bin]]
name = "force-build"
path = "main.rs"
