[workspace]
members = [
    "egui-pysync-server",
    "egui-pysync-client",
    "egui-pysync-common",
    "egui-pysync-macros",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
egui_pysync_common = { path = "egui-pysync-common" }
