[workspace]
members = ["egui-pysync-macros"]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"

[package]
name = "egui_pysync"
edition.workspace = true

[features]
server = []

[dependencies]
egui_pysync_macros = { path = "egui-pysync-macros" }
postcard = { version = "1.1.1", features = ["use-std"] }
egui = "*"
serde = "*"
heapless = "0.7"
pyo3 = { version = "0.23.3", features = ["extension-module"] }
