[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "egui_pysync"
requires-python = ">=3.11"
# license = { file = "LICENSE" }
# dynamic = ["version"]
version = "0.1.0"

dependencies = ["numpy"]

[tool.setuptools]
packages = ["egui_pysync"]

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
select = ["E", "F", "W", "D", "N", "PL", "UP", "NPY"]
pydocstyle.convention = "google"

unfixable = [
    "F401", # unused-imports
]

# ignore = [
#     "PLR0904", # too-many-public-methods
#     "PLR0913", # too-many-arguments
#     "PLR2004", # magic-value-comparison
#     "PLR0917", # too-many-positional
#     "D100",    # undocumented-public-module
# ]
