[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "egui-pysync"
description = "A Python library for egui-pysync project."
authors = [{ name = "Vojtech Homola", email = "vojhom@outlook.cz" }]
requires-python = ">=3.12"
license = { file = "LICENSE" }
dynamic = ["version"]
readme = "README.md"

dependencies = ["numpy"]

[dependency-groups]
dev = ["ipython", "matplotlib"]

[tool.hatch.version]
path = "egui_pysync/version.py"

[tool.hatch.build]
packages = ["egui_pysync"]
ignore-vcs = true

[tool.uv]
workspace.members = ["examples/images_states"]

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
select = ["E", "F", "W", "D", "N", "PL", "UP", "NPY"]
pydocstyle.convention = "google"

unfixable = [
    "F401", # unused-imports
]

ignore = [
    "PLR0904", # too-many-public-methods
    "PLR0913", # too-many-arguments
    "PLR2004", # magic-value-comparison
    "PLR0917", # too-many-positional
    "PLR0912", # too-many-branches
    "D100",    # undocumented-public-module
]
