[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "egui-pysync"
description = "A Python library for egui-pysync project."
authors = [{ name = "Vojtěch Homola", email = "vojhom@outlook.cz" }]
requires-python = ">=3.12"
license = { file = "LICENSE" }
dynamic = ["version"]
readme = "README.md"

dependencies = ["numpy"]

[tool.setuptools]
packages = ["egui_pysync"]
dynamic.version = { attr = "egui_pysync.__version__" }

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
select = ["E", "F", "W", "D", "N", "PL", "UP", "NPY"]
pydocstyle.convention = "google"

unfixable = [
    "F401", # unused-imports
]

ignore = [
    "PLR0904", # too-many-public-methods
    "PLR0913", # too-many-arguments
    "PLR2004", # magic-value-comparison
    "PLR0917", # too-many-positional
    "PLR0912", # too-many-branches
    "D100",    # undocumented-public-module
]
