[build-system]
requires = ["maturin>=1.7"]
build-backend = "maturin"

[project]
name = "expert_ui"
# description = "Algorithms for processing the data from scanning transmission electron microscope."
# urls.repository = "https://github.com/tescan-orsay-holding/stem-measurements"
requires-python = ">=3.11"
# license = { file = "LICENSE" }
classifiers = ["Programming Language :: Python", "Programming Language :: Rust"]
dynamic = ["version"]

dependencies = ["numpy"]

[tool.maturin]
module-name = "expert_ui.core"
features = ["server"]
bindings = "pyo3"


[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
select = ["E", "F", "W", "D", "N", "PL", "UP", "NPY"]
pydocstyle.convention = "google"

unfixable = [
    "F401", # unused-imports
]

ignore = [
    "PLR0904", # too-many-public-methods
    "PLR0913", # too-many-arguments
    "PLR2004", # magic-value-comparison
    "PLR0917", # too-many-positional
    "D100",    # undocumented-public-module
]
