[build]
target = "./example/showcase/gui/index.html"
dist = "./example/showcase/gui/web/"
filehash = false

[serve]
port = 8090

[watch]
watch = ["./example/showcase/gui-core/", "./example/showcase/gui/", "./crates/egui-states/src/client/"]
ignore = ["./example/showcase/gui/web/"]
