[package]
name = "counter_server"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "counter-server"
path = "main.rs"

[dependencies]
egui_states = { path = "../../../crates/egui-states", default-features = false, features = ["server"] }
tokio = { version = "1.52", features = ["rt", "signal"] }

[build-dependencies]
counter_gui = { path = "../gui" }
egui_states = { workspace = true, features = ["build_scripts"] }
