[package]
name = "egui_pyserver"
version.workspace = true
edition.workspace = true

[dependencies]
# pyo3 = { version = "0.22.*", features = ["extension-module", "abi3-py311"] }
pyo3 = { version = "0.22.*" }
egui_pysync = { workspace = true }
